export const locations = [
  "Mumbai", "Delhi", "Bangalore", "Hyderabad", "Ahmedabad", "Chennai", "Kolkata", "Surat", "Pune", "Jaipur", "Lucknow",
  "Kanpur", "Nagpur", "Indore", "Thane", "Bhopal", "Visakhapatnam", "Pimpri-Chinchwad", "Patna", "Vadodara", "Ghaziabad",
  "Ludhiana", "Agra", "Nashik", "Faridabad", "Meerut", "Rajkot", "Kalyan-Dombivli", "Vasai-Virar", "Varanasi", "Srinagar",
  "Aurangabad", "Dhanbad", "Amritsar", "Navi Mumbai", "Allahabad", "Howrah", "Gwalior", "Jabalpur", "Coimbatore",
  "Vijayawada", "Jodhpur", "Madurai", "Raipur", "Kota", "Chandigarh", "Guwahati", "Solapur", "Hubballi-Dharwad", "Bareilly",
  "Moradabad", "Mysore", "Gurgaon", "Aligarh", "Jalandhar", "Tiruchirappalli", "Bhubaneswar",
  "Salem", "Mira-Bhayandar", "Warangal", "Thiruvananthapuram", "Bhiwandi", "Saharanpur", "Guntur", "Amravati", "Bikaner", "Noida", "Jamshedpur",
  "Bhilai", "Cuttack", "Firozabad", "Kochi", "Nellore", "Bhavnagar", "Dehradun", "Durgapur", "Asansol", "Rourkela", "Nanded", "Kolhapur", "Ajmer",
  "Akola", "Gulbarga", "Jamnagar", "Ujjain", "Loni", "Siliguri", "Jhansi", "Ulhasnagar",
  "Nellore", "Sangli", "Satara", "Akola", "Jalgoan", "Nagar", "New Delhi", "Goa", "Nanded", "Dhule",
  "Jammu",
  "Sangli",
  "Belgaum",
  "Mangalore",
  "Ambattur",
  "Tirunelveli",
  "Malegaon",
  "Gaya",
  "Udaipur",
  "Davanagere",
  "Kozhikode",
  "Maheshtala",
  "Rajpur Sonarpur",
  "Kollam",
  "Bokaro",
  "South Dumdum",
  "Gopalpur",
  "Ahmednagar",
  "Rajahmundry",
  "Berhampur",
  "Tirupati",
  "Pondicherry",
  "Agartala",
  "Karnal",
  "Bihar Sharif",
  "Panipat",
  "Darbhanga",
  "Bally",
  "Aizawl",
  "Dewas",
  "Ichalkaranji",
  "Kakinada",
  "Bidhannagar",
  "Jharsuguda",
  "Bharuch",
  "Pali",
  "Satna",
  "Bilaspur",
  "Shimla",
  "Anantapur",
  "Nizamabad",
  "Hajipur",
  "Muzaffarnagar",
  "Bhagalpur",
  "Korba",
  "Rampur",
  "Etawah",
  "Sonipat",
  "Khandwa",
  "Alwar",
  "Tumkur",
  "Chittoor",
  "Sikar",
  "Rohtak",
  "Bardhaman",
  "Gandhinagar",
  "Bathinda",
  "Serampore",
  "Mehsana",
  "Hapur",
  "Anand",
  "Bulandshahr",
  "Raichur",
  "Sitapur",
  "Hindupur",
  "Farrukhabad",
  "Ongole",
  "Bijapur",
  "Mirzapur",
  "Jaunpur",
  "Siwan",
  "Bhuj",
  "Bhimavaram",
  "Krishnanagar",
  "Kumbakonam",
  "Rewa",
  "Kolar",
  "Shivpuri",
  "Chinsurah",
  "Chhapra",
  "Porbandar",
  "Dindigul", "Hoshangabad", "Kottayam", "Chandrapur", "Baranagar", "Darjeeling", "Motihari", "Nagaon", "Kharagpur", "Bettiah", "Kanchipuram", "Raigarh", "Palakkad", "Bongaigaon", "Deoghar", "Dibrugarh", "Guntur", "Faizabad", "Bishnupur", "Sambalpur", "Purnia", "Raiganj", "Karimnagar", "Nadiad", "Malda",
  "Tinsukia", "Bidar", "Sultanpur", "Munger", "Shillong", "Imphal", "Tezpur", "Kohima", "Dimapur"

];
